config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
	resources :articles do
		resources :comments
	end
	resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image, styles: { medium: "150x150>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings, dependent: :destroy
	has_many :articles, through: :taggings
	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	def index
		@articles = Article.all
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end
	def new
		@article = Article.new
	end
	def create
		@article = Article.new(article_params)
		@article.save
		flash.notice = "Article created!"
		redirect_to article_path(@article)
	end
	def edit
		@article = Article.find(params[:id])
		@article.save
	end
	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		flash.notice = "Article '#{@article.title}' updated."
		redirect_to article_path(@article)
	end
	def destroy
		@article = Article.find(params[:id])
		@article.delete
		flash.notice = "Article '#{@article.title}' deleted."
		redirect_to articles_url
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save
		redirect_to article_path(@comment.article)
	end

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find(params[:id])
	end
	def index
		@tags = Tag.all
	end
	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy
		flash.notice = "Tag '#{@tag.id}' deleted."
		redirect_to tags_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
		def article_params
			params.require(:article).permit(:title, :body, :tag_list, :image)
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
	<div class='comment_body'>
		<h4><div class='comment_author'><%= comment.author_name %> commented:</div></h4>
		<p><%= comment.body %></p>
		<p><div class='comment_time'>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</div></p>
	</div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
<ul>
	<% @article.errors.full_messages.each do |error| %>
	<li><%= error %></li>
	<% end %>
</ul>
<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :body %><br />
	<%= f.text_area :body %>
</p>
<p>
	<%= f.label :tag_list %><br />
	<%= f.text_field :tag_list %>
</p>
<p>
	<% if @article.image.exists? %>
		<%= image_tag @article.image.url(:medium) %><br/>
	<% end %>
   <%= f.label :image, "Attach an Image" %><br />
   <%= f.file_field :image %>
<p>
	<%= f.submit %>
</p>
<%= link_to "<< Back to articles", articles_path, class: 'back_to_articles_button' %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
		<%= link_to article.title, article_path(article) %>
	</li>
  <% end %>
	<%= link_to 'Create new article.', new_article_path, class: "new_article" %>
</ul>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<div class='display_tags'>
			Tags:
			<% @article.tags.each do |tag| %>
				<%= link_to tag.name, tag_path(tag) %>
			<% end %>
	</div>
</p>
<p>
	<% if @article.image.exists? %>
		<%= image_tag @article.image.url(:medium) %><br/>
	<% end %>
<p><h3><%= @article.body %></h3></p>
<p><div class='time_edited'>Article posted: <%= @article.updated_at %></div></p>
<%= link_to "Edit this article", edit_article_path(@article), class: "edit_article_button" %>
<h3><div class='comment_title'>Comments (<%= @article.comments.size %> total)</div></h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>
<%= link_to "<< Back to Articles List", articles_path, class: "back_to_articles_list_link" %>
<%= link_to "Delete this article...", article_path(@article), data: {confirm: "Are you sure?"}, method: :delete, class: "delete_article_button" %>

app/views/comments/_form.html.erb
<div class='comment_form'>
		<h3>Post a comment</h3>
		<%= form_for [ @article, @comment ] do |f| %>
		<p>
				<%= f.label :author_name, 'Your name' %><br/>
				<%= f.text_field :author_name %>
		</p>
		<p>
				<%= f.label :body, 'Your comment' %><br/>
				<%= f.text_area :body %>
		</p>
		<p>
				<%= f.submit 'Submit' %>
		</p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arrow Computing Tech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All tags</h1>

<ul class='tag_list'>
	<% @tags.each do |tag| %>
		<li class='article_tag_list'>
			<%= link_to tag.name, tag_path(tag) %>
		</li>
	<% end %>
</ul>
<%= link_to "<< Back to articles list", articles_path, class: "back_to_articles_list_link" %>

app/views/tags/show.html.erb
<p>
   <h1>Articles tagged with <%= @tag.name %></h1>

   <ul>
	  <% @tag.articles.each do |article| %>
		<h3><li class='article_tag_list'><%= link_to article.title, article_path(article) %></li><h3>
		<%= link_to "Delete this tag", tag_path(@tag), data: {confirm: "Are you sure?"}, method: :delete, class: "delete_tag_button" %>
	  <% end %>
   </ul>
</p>
<p><h5><%= link_to "View all tags", tags_path, class: "view_all_tags" %></h3></p>